server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://jlxdjedwmyokwj:913a645cff7db6aa4fb5374624ef146c4d615cc7b9c08e062981b6cf289e7361@ec2-34-232-191-133.compute-1.amazonaws.com:5432/dejckhp43vspeg
    username: jlxdjedwmyokwj
    password: 913a645cff7db6aa4fb5374624ef146c4d615cc7b9c08e062981b6cf289e7361
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
